# Playbook for deploying Google Chrome of Buo-ren Lin's
# preferred operating system to the managed nodes
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+
- name: Deploy Google Chrome to the managed nodes
  hosts: all
  environment: {}
    # Set these environment variables if you need to access the
    # internet via an HTTP/HTTPS proxy service
    #http_proxy: http://192.168.49.1:8228
    #https_proxy: http://192.168.49.1:8228
  tasks:
    - name: Import corresponding task of the role
      ansible.builtin.import_role:
        name: brlin.brlin_os_customizations
        tasks_from: deploy-google-chrome.yml
